### ISSUE TITLE
Mouvements buggés

### ISSUE THREAD

**Issue by fg1989** [NB0174/AbricotGame#45]
Parfois en sortant d'un combat, les mouvement se comportent de manière très étrange. Comme je n'arrive pas a reproduire le bug je ne suis pas en mesure de le régler.

**Comment by NB0174** [comment]
On l'a pas réparée celle la ?

**Comment by leoTigers** [comment]
non

**Comment by fg1989** [comment]
Le bug est encore la meme si il est rès rare

**Comment by fg1989** [comment]
Ancien probleme en python
reglé parle cpp
